---
abstract: 'Print HTML tables from Perl data'
author:
  - 'Nic Wolff <nic@angel.net>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-DataTable
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 0
  HTML::FromArrayref: 0
  Test::More: 0
version: 0.53
